In [1]:
import pandas as pd
import numpy as np

# LOAD THE DATASET

In [2]:
df=pd.read_csv('dataset_website.csv')
df.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [3]:
df.shape

(11055, 32)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

In [5]:
df.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [6]:
df.describe()

index  having_IPhaving_IP_Address  URLURL_Length  \
count  11055.000000                11055.000000   11055.000000   
mean    5528.000000                    0.313795      -0.633198   
std     3191.447947                    0.949534       0.766095   
min        1.000000                   -1.000000      -1.000000   
25%     2764.500000                   -1.000000      -1.000000   
50%     5528.000000                    1.000000      -1.000000   
75%     8291.500000                    1.000000      -1.000000   
max    11055.000000                    1.000000       1.000000   

       Shortining_Service  having_At_Symbol  double_slash_redirecting  \
count        11055.000000      11055.000000              11055.000000   
mean             0.738761          0.700588                  0.741474   
std              0.673998          0.713598                  0.671011   
min             -1.000000         -1.000000                 -1.000000   
25%              1.000000          1.000000                  1.000000   
50%              1.000000          1.000000                  1.000000   
75%              1.000000          1.000000                  1.000000   
max              1.000000          1.000000                  1.000000   

       Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
count   11055.000000       11055.000000    11055.000000   
mean       -0.734962           0.063953        0.250927   
std         0.678139           0.817518        0.911892   
min        -1.000000          -1.000000       -1.000000   
25%        -1.000000          -1.000000       -1.000000   
50%        -1.000000           0.000000        1.000000   
75%        -1.000000           1.000000        1.000000   
max         1.000000           1.000000        1.000000   

       Domain_registeration_length  ...   popUpWidnow        Iframe  \
count                 11055.000000  ...  11055.000000  11055.000000   
mean                     -0.336771  ...      0.613388      0.816915   
std                       0.941629  ...      0.789818      0.576784   
min                      -1.000000  ...     -1.000000     -1.000000   
25%                      -1.000000  ...      1.000000      1.000000   
50%                      -1.000000  ...      1.000000      1.000000   
75%                       1.000000  ...      1.000000      1.000000   
max                       1.000000  ...      1.000000      1.000000   

       age_of_domain     DNSRecord   web_traffic     Page_Rank  Google_Index  \
count   11055.000000  11055.000000  11055.000000  11055.000000  11055.000000   
mean        0.061239      0.377114      0.287291     -0.483673      0.721574   
std         0.998168      0.926209      0.827733      0.875289      0.692369   
min        -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
25%        -1.000000     -1.000000      0.000000     -1.000000      1.000000   
50%         1.000000      1.000000      1.000000     -1.000000      1.000000   
75%         1.000000      1.000000      1.000000      1.000000      1.000000   
max         1.000000      1.000000      1.000000      1.000000      1.000000   

       Links_pointing_to_page  Statistical_report        Result  
count            11055.000000        11055.000000  11055.000000  
mean                 0.344007            0.719584      0.113885  
std                  0.569944            0.694437      0.993539  
min                 -1.000000           -1.000000     -1.000000  
25%                  0.000000            1.000000     -1.000000  
50%                  0.000000            1.000000      1.000000  
75%                  1.000000            1.000000      1.000000  
max                  1.000000            1.000000      1.000000  

[8 rows x 32 columns]

# Splitting the data

In [7]:
x=df.iloc[:,0:31].values
y=df.iloc[:,-1].values

In [8]:
x

array([[    1,    -1,     1, ...,     1,     1,    -1],
       [    2,     1,     1, ...,     1,     1,     1],
       [    3,     1,     0, ...,     1,     0,    -1],
       ...,
       [11053,     1,    -1, ...,     1,     0,     1],
       [11054,    -1,    -1, ...,     1,     1,     1],
       [11055,    -1,    -1, ...,    -1,     1,    -1]], dtype=int64)

In [9]:
y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train

array([[ 5034,     1,    -1, ...,     1,     1,     1],
       [10308,     1,     1, ...,     1,     0,     1],
       [ 7564,    -1,    -1, ...,     1,     1,    -1],
       ...,
       [ 9846,    -1,     1, ...,     1,     1,     1],
       [10800,    -1,    -1, ...,     1,     1,     1],
       [ 2733,     1,    -1, ...,     1,     1,     1]], dtype=int64)

In [12]:
x_test

array([[ 227,    1,   -1, ...,    1,    0,    1],
       [2253,    1,   -1, ...,    1,    0,    1],
       [2647,    1,   -1, ...,    1,    1,    1],
       ...,
       [6811,   -1,   -1, ...,    1,    1,    1],
       [4722,    1,   -1, ...,    1,    0,    1],
       [ 326,    1,   -1, ...,    1,    1,    1]], dtype=int64)

In [13]:
y_train

array([ 1, -1, -1, ...,  1, -1, -1], dtype=int64)

In [14]:
y_test

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

# Building the Model


# 1.DecisionTree

In [15]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [16]:
model.fit(x_train,y_train) 

DecisionTreeClassifier()

In [17]:
train_pred = model.predict(x_train)
train_pred

array([ 1, -1, -1, ...,  1, -1, -1], dtype=int64)

In [18]:
test_pred = model.predict(x_test)
test_pred

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [20]:
print('Training accuracy : ',accuracy_score(y_train,train_pred))
print('Testing accuracy : ',accuracy_score(y_test,test_pred))

Training accuracy :  1.0
Testing accuracy :  0.9511533242876526


# 2.KNeighborsClassifier

In [21]:
from sklearn.neighbors import KNeighborsClassifier
Kn =KNeighborsClassifier()

In [22]:
Kn.fit(x_train,y_train)

KNeighborsClassifier()

In [23]:
y_pred = Kn.predict(x_test)
y_pred

array([-1, -1, -1, ...,  1, -1,  1], dtype=int64)

In [24]:
y_pred1 = Kn.predict(x_train)
y_pred1

array([ 1, -1,  1, ...,  1,  1,  1], dtype=int64)

In [25]:
print('Training accuracy: ',accuracy_score(y_train,y_pred1))
print('Testing accuracy: ',accuracy_score(y_test,y_pred))

Training accuracy:  0.7800768882858435
Testing accuracy:  0.6142017186793306


# 3. LogisticRegression

In [26]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [27]:
lr.fit(x_train,y_train)


C:\Users\MOHAN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
lr_test_pred= lr.predict(x_test)
lr_test_pred

array([-1, -1,  1, ..., -1, -1,  1], dtype=int64)

In [29]:
lr_train_pred = lr.predict(x_train)
lr_train_pred


array([ 1, -1, -1, ...,  1, -1,  1], dtype=int64)

In [49]:
print('Training accuracy: ',accuracy_score(y_train,lr_train_pred))
print('Testing accuracy: ',accuracy_score(y_test,lr_test_pred))

Training accuracy:  0.9272953414744459
Testing accuracy:  0.9176843057440073


# 4.GaussianNB

In [31]:
from sklearn.naive_bayes import GaussianNB
Gb = GaussianNB()

In [32]:
Gb.fit(x_train,y_train)

GaussianNB()

In [33]:
pred_test = Gb.predict(x_test)

In [34]:
pred_train = Gb.predict(x_train)

In [35]:
print('Training accuracy: ', accuracy_score(y_train,pred_train))
print('Testing accuracy: ', accuracy_score(y_test,pred_test))

Training accuracy:  0.8870420624151968
Testing accuracy:  0.8801447308909995


# 5.RandomForestClassifier

In [36]:
from sklearn.ensemble import RandomForestClassifier
Rn =RandomForestClassifier()

In [37]:
Rn.fit(x_train,y_train)

RandomForestClassifier()

In [38]:
Rn_test_pred = Rn.predict(x_test)

In [39]:
Rn_train_pred = Rn.predict(x_train)

In [40]:
print('Training accuracy: ',accuracy_score(y_train,Rn_train_pred))
print('Testing accuracy: ' , accuracy_score(y_test,Rn_test_pred))

Training accuracy:  1.0
Testing accuracy:  0.9656264133876075


Based on Traing and Testing accuracy , we prefer Logistic Regression for the model
(DecisionTree and RandomForest has 1.0 training accuracy value may cause override problem).

# Create the pickle file

In [81]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))